# docker compose up --build

services:
  jupyter:
    build:
      context: .
    ports:
      - 8889:8888
    volumes:
      - ./:/home/jovyan/work
    command: start-notebook.py --NotebookApp.token='my-token'
    # command: start-notebook.py   # with a generated token
